from datetime import datetime

import pytest

from app.domain.user.entities import User
from app.infrastructure.repositories.sqlalchemy.user.user_repo import (
    SQLAlchemyUserRepository,
)
from app.presentation.error_handlers.integrity_error import IntegrityError


class TestSQLAlchemyUserRepository:
    """Test suite for SQLAlchemyUserRepository with in-memory database."""

    def test_repository_initialization(self, test_db_session):
        """Test repository initializes correctly."""
        repo = SQLAlchemyUserRepository(db_session=test_db_session)
        assert repo.db_session == test_db_session

    def test_create_user_successfully(self, test_db_session):
        """Test creating a user successfully."""
        repo = SQLAlchemyUserRepository(db_session=test_db_session)

        user = User(
            id=None,  # ID will be generated by DB
            name="Test User",
            email="test@example.com",
            password="$argon2id$v=19$m=65540,t=3,p=4$test$test123",
            is_active=True,
            is_super_admin=False,
            creation_date=datetime.now(),
            update_date=None
        )

        created_user = repo.create(user=user)

        assert created_user.id is not None
        assert created_user.name == user.name
        assert created_user.email == user.email
        assert created_user.is_active == user.is_active
        assert created_user.is_super_admin == user.is_super_admin

    def test_create_user_with_all_fields(self, test_db_session):
        """Test creating a user with all fields populated."""
        repo = SQLAlchemyUserRepository(db_session=test_db_session)

        now = datetime.now()
        user = User(
            id=None,
            name="Admin User",
            email="admin@example.com",
            password="$argon2id$v=19$m=65540,t=3,p=4$test$admin",
            is_active=True,
            is_super_admin=True,
            creation_date=now,
            update_date=None
        )

        created_user = repo.create(user=user)

        assert created_user.is_super_admin is True
        assert created_user.creation_date is not None

    def test_create_multiple_users(self, test_db_session):
        """Test creating multiple users."""
        repo = SQLAlchemyUserRepository(db_session=test_db_session)

        users_data = [
            User(
                id=None,
                name="User One",
                email="one@example.com",
                password="hash1",
                is_active=True,
                is_super_admin=False,
                creation_date=datetime.now(),
                update_date=None
            ),
            User(
                id=None,
                name="User Two",
                email="two@example.com",
                password="hash2",
                is_active=True,
                is_super_admin=False,
                creation_date=datetime.now(),
                update_date=None
            ),
        ]

        created_users = []
        for user in users_data:
            # Create new session for each user since repo closes the session
            from sqlalchemy.orm import sessionmaker
            TestSession = sessionmaker(bind=test_db_session.get_bind())
            new_session = TestSession()
            repo = SQLAlchemyUserRepository(db_session=new_session)
            created_user = repo.create(user=user)
            created_users.append(created_user)

        assert len(created_users) == 2
        assert created_users[0].name == "User One"
        assert created_users[1].name == "User Two"

    def test_create_user_with_duplicate_email(self, test_db_session, mock_user_schema):
        """Test that creating user with duplicate email raises IntegrityError."""
        repo = SQLAlchemyUserRepository(db_session=test_db_session)

        # Try to create user with same email as mock_user_schema
        user = User(
            id=None,
            name="Different User",
            email="db@example.com",  # Same email as mock_user_schema
            password="different_hash",
            is_active=True,
            is_super_admin=False,
            creation_date=datetime.now(),
            update_date=None
        )

        with pytest.raises(IntegrityError):
            repo.create(user=user)

    def test_session_is_closed_after_create(self, test_db_session):
        """Test that create operation completes without errors."""
        # Create a new session for the repo operation
        from sqlalchemy.orm import sessionmaker
        TestSession = sessionmaker(bind=test_db_session.get_bind())
        new_session = TestSession()

        repo = SQLAlchemyUserRepository(db_session=new_session)

        user = User(
            id=None,
            name="Test User",
            email="test@example.com",
            password="hash",
            is_active=True,
            is_super_admin=False,
            creation_date=datetime.now(),
            update_date=None
        )

        # Should complete without error
        created_user = repo.create(user=user)
        assert created_user.id is not None

    def test_created_user_has_generated_id(self, test_db_session):
        """Test that created user has an ID generated by the database."""
        repo = SQLAlchemyUserRepository(db_session=test_db_session)

        user = User(
            id=None,
            name="No ID User",
            email="noid@example.com",
            password="hash",
            is_active=True,
            is_super_admin=False,
            creation_date=datetime.now(),
            update_date=None
        )

        created_user = repo.create(user=user)

        assert created_user.id is not None
        assert isinstance(created_user.id, int)
        assert created_user.id > 0

    def test_user_fields_match_after_create(self, test_db_session):
        """Test that user fields match exactly after creation."""
        repo = SQLAlchemyUserRepository(db_session=test_db_session)

        original_user = User(
            id=None,
            name="John Doe",
            email="john@example.com",
            password="$argon2id$v=19$m=65540,t=3,p=4$test$hash",
            is_active=True,
            is_super_admin=False,
            creation_date=datetime.now(),
            update_date=None
        )

        created_user = repo.create(user=original_user)

        assert created_user.name == original_user.name
        assert created_user.email == original_user.email
        assert created_user.password == original_user.password
        assert created_user.is_active == original_user.is_active
        assert created_user.is_super_admin == original_user.is_super_admin
